CREATE ROLE IF NOT EXISTS BookDBUser;

DROP DATABASE IF EXISTS `BookDB`;
SET default_storage_engine=InnoDB;
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS BookDB
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE BookDB;

GRANT SELECT, INSERT, UPDATE, DELETE, FILE ON *.* TO BookDBUser;
GRANT ALL PRIVILEGES ON *.* TO BookDBUser;
GRANT ALL PRIVILEGES ON `BookDB`.* TO BookDBUser;
FLUSH PRIVILEGES;

CREATE TABLE `Quotes` (
	`QuoteID` INT NOT NULL AUTO_INCREMENT,
	`Title` VARCHAR(100) NOT NULL,
    `Author` VARCHAR(100) NOT NULL,
	`Quote` VARCHAR(8192) NOT NULL,
	PRIMARY KEY (`QuoteID`) 
);

CREATE TABLE `QuoteTags` (
	`QuoteID` INT NOT NULL,
	`Tag` VARCHAR(50),
	PRIMARY KEY (QuoteID, Tag)
);

CREATE TABLE `Tags` (
	`Tag` VARCHAR(50) NOT NULL,
	PRIMARY KEY (Tag)
);

ALTER TABLE QuoteTags
ADD CONSTRAINT fk_QuoteTags_QuoteID_Quotes_QuoteID FOREIGN KEY (QuoteID) REFERENCES Quotes (QuoteID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE QuoteTags
ADD CONSTRAINT fk_QuoteTags_Tag_Tags_Tag FOREIGN KEY (Tag) REFERENCES Tags (Tag) ON DELETE CASCADE ON UPDATE CASCADE;

SELECT * FROM Tags;
INSERT INTO Tags VALUES ("Business");
INSERT INTO Tags VALUES ("Career");
INSERT INTO Tags VALUES ("Discipline");
INSERT INTO Tags VALUES ("Exercise");
INSERT INTO Tags VALUES ("Failure");
INSERT INTO Tags VALUES ("Finance");
INSERT INTO Tags VALUES ("Friendship");
INSERT INTO Tags VALUES ("Growth");
INSERT INTO Tags VALUES ("Learning");
INSERT INTO Tags VALUES ("Mentorship");
INSERT INTO Tags VALUES ("New Job");
INSERT INTO Tags VALUES ("Networking");
INSERT INTO Tags VALUES ("Philosophy");
INSERT INTO Tags VALUES ("Programming");
INSERT INTO Tags VALUES ("Purpose");
INSERT INTO Tags VALUES ("Relationships");
INSERT INTO Tags VALUES ("Social");
INSERT INTO Tags VALUES ("Social Intelligence");
INSERT INTO Tags VALUES ("Technology");
INSERT INTO Tags VALUES ("Travel");


